/*
 * Regenerate src/data/products.js from:
 *   - src/data/products.json           (source catalog)
 *   - scripts/product_image_manifest.json  (generated by build_product_images.py)
 *
 * Produces a single canonical data module with the full product shape used
 * across the site (ProductCard, PDP, admin store, home rails, etc.).
 *
 * Run: node scripts/build_products_js.cjs
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PRODUCTS_JSON = path.join(ROOT, 'src/data/products.json');
const MANIFEST = path.join(ROOT, 'scripts/product_image_manifest.json');
const OUTPUT = path.join(ROOT, 'src/data/products.js');

const PLACEHOLDER_IMAGE = '/products/_placeholder.jpg';

// Keep the canonical category list in sync with src/store/categoryStore.js.
const CATEGORY_META = [
  { id: 'cat_sofas', name: 'Sofas & Sofa Sets', slug: 'sofas' },
  { id: 'cat_beds', name: 'Beds', slug: 'beds' },
  { id: 'cat_office', name: 'Office Chairs', slug: 'office-chairs' },
  { id: 'cat_gaming', name: 'Gaming Chairs', slug: 'gaming-chairs' },
  { id: 'cat_cafe', name: 'Cafe Chairs', slug: 'cafe-chairs' },
  { id: 'cat_rocking', name: 'Rocking Chairs', slug: 'rocking-chairs' },
  { id: 'cat_dining', name: 'Dining Tables & Sets', slug: 'dining' },
  { id: 'cat_bar', name: 'Bar Units & Bar Tables', slug: 'bar-units' },
  { id: 'cat_console', name: 'Console Tables', slug: 'console-tables' },
  { id: 'cat_dressing', name: 'Dressing Tables', slug: 'dressing-tables' },
  { id: 'cat_side', name: 'Side Tables / Nightstands', slug: 'side-tables' },
  { id: 'cat_tea', name: 'Tea Tables', slug: 'tea-tables' },
  { id: 'cat_wardrobe', name: 'Wardrobes', slug: 'wardrobes' },
  { id: 'cat_mirror', name: 'Mirrors', slug: 'mirrors' },
  { id: 'cat_cabinet', name: 'Utility Cabinets', slug: 'cabinets' },
  { id: 'cat_curtain', name: 'Curtains', slug: 'curtains' },
  { id: 'cat_accessories', name: 'Accessories', slug: 'accessories' },
];
const CAT_BY_ID = Object.fromEntries(CATEGORY_META.map((c) => [c.id, c]));

// Classify a product into a (categoryId, subcategory) tuple. Priority: name
// first (most specific), then the JSON category label, then the image folder.
function classify(raw) {
  const nameU = (raw.name || '').toUpperCase();
  const catU = (raw.category || '').toUpperCase();
  const folderU = (raw.image_folder || '').toUpperCase();
  const hay = `${nameU} | ${catU} | ${folderU}`;

  // Specific subtypes first.
  if (/GAMING\s*CHAIR/.test(hay)) return ['cat_gaming', 'Gaming Chair'];
  if (/EXECUTIVE\s*CHAIR|BOSS\s*OFFICE|OFFICE\s*CHAIR/.test(hay)) return ['cat_office', 'Office Chair'];
  if (/VISITOR\s*CHAIR/.test(hay)) return ['cat_office', 'Visitor Chair'];
  if (/ROCKING/.test(hay)) return ['cat_rocking', 'Rocking Chair'];
  if (/CAFE|BAR\s*STOOL|STOOL/.test(hay)) return ['cat_cafe', 'Cafe Chair'];

  if (/BAR\s*UNIT|BAR\s*TABLE/.test(hay)) return ['cat_bar', 'Bar Unit'];
  if (/DINING\s*TABLE|DINNING\s*SET|DINNING/.test(hay)) return ['cat_dining', 'Dining Set'];
  if (/TEA\s*TABLE|COFFEE\s*TABLE|LOW\s*TABLE|BED\s*TRAY|ASTHETIC\s*SOFA\s*TABLE/.test(hay)) return ['cat_tea', 'Tea Table'];
  if (/CONSOLE/.test(hay)) return ['cat_console', 'Console Table'];
  if (/DRESSING/.test(hay)) return ['cat_dressing', 'Dressing Table'];
  if (/NIGHTSTAND|NIGHT\s*STAND|SIDE\s*TABLE/.test(hay)) return ['cat_side', 'Side Table'];
  if (/FLOATING\s*SHELF|CORNER\s*SHELF|SHELF|WALL\s*BRACKET/.test(hay)) return ['cat_cabinet', 'Shelf'];

  if (/WARDROBE/.test(hay)) return ['cat_wardrobe', 'Wardrobe'];
  if (/MIRROR/.test(hay)) return ['cat_mirror', 'Mirror'];
  if (/UTILITY\s*CABINET|CABINET/.test(hay)) return ['cat_cabinet', 'Utility Cabinet'];

  if (/CURTAIN/.test(hay)) return ['cat_curtain', 'Curtain'];

  if (/KING\s*SIZE|QUEEN\s*SIZE|\bBED\b/.test(hay)) return ['cat_beds', 'Bed'];

  if (/SOFA/.test(hay)) return ['cat_sofas', 'Sofa'];
  if (/CHAIR/.test(hay)) return ['cat_office', 'Chair'];

  if (/TABLE/.test(hay)) return ['cat_side', 'Table'];

  return ['cat_accessories', raw.category || 'Accessory'];
}

// Title-case a string like "SOFA SET" → "Sofa Set". Preserves apostrophes etc.
function titleCase(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/\b([a-z])/g, (_, c) => c.toUpperCase())
    .replace(/\s+/g, ' ')
    .trim();
}

function slugify(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

// Expand dimensions "6X6.5 FT" or similar. Otherwise fall back to details.
function parseDimensions(raw) {
  const details = raw.dimensions === 'Standard' || !raw.dimensions
    ? ''
    : String(raw.dimensions);
  return {
    height: '',
    width: '',
    depth: '',
    seatHeight: '',
    details: details || 'Standard',
  };
}

// Convert "3-digit-comma" price to integer.
function parsePrice(p) {
  if (typeof p === 'number') return p;
  if (!p) return 0;
  return parseInt(String(p).replace(/[^0-9]/g, ''), 10) || 0;
}

// Dedupe by id, keeping the most informative entry.
function dedupe(products) {
  const by = new Map();
  for (const p of products) {
    const existing = by.get(p.id);
    if (!existing) {
      by.set(p.id, p);
      continue;
    }
    const pScore = (p.name && p.name !== 'Unknown Product' ? 2 : 0) + (p.price > 0 ? 1 : 0);
    const eScore = (existing.name && existing.name !== 'Unknown Product' ? 2 : 0) + (existing.price > 0 ? 1 : 0);
    if (pScore > eScore) by.set(p.id, p);
  }
  return [...by.values()];
}

// ---------------------------------------------------------------------------

const raw = JSON.parse(fs.readFileSync(PRODUCTS_JSON, 'utf8'));
const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));

const unique = dedupe(raw);

// Stable ordering: by campaign then by numeric tail.
unique.sort((a, b) => {
  const [ac, an] = a.id.split('-');
  const [bc, bn] = b.id.split('-');
  if (ac !== bc) return ac.localeCompare(bc);
  return parseInt(an, 10) - parseInt(bn, 10);
});

const now = new Date('2026-04-26T08:00:00Z').toISOString();
const categoryCounts = {};
let featuredCount = 0;

const products = unique
  .filter((p) => p.name && p.name !== 'Unknown Product')
  .map((p, idx) => {
    const [categoryId, subcategory] = classify(p);
    const cat = CAT_BY_ID[categoryId];

    const imgs = manifest[p.id] || [];
    const images = imgs.length ? imgs : [PLACEHOLDER_IMAGE];
    // Lifestyle = last image if we have 2+, else first.
    const lifestyleImage = images.length > 1 ? images[images.length - 1] : images[0];

    const name = titleCase(p.name);
    const slug = `${slugify(name)}-${p.id.toLowerCase()}`;
    const price = parsePrice(p.price);

    // Basic popularity: higher for priced items, with a stable per-id jitter.
    const hashJit = ((p.id.charCodeAt(0) * 31 + p.id.charCodeAt(p.id.length - 1)) % 15);
    const popularity = price > 0 ? 80 + hashJit : 60 + hashJit;

    // Feature a balanced set across categories: 1 in every 4 products.
    const featured = idx % 4 === 0;
    if (featured) featuredCount += 1;
    categoryCounts[cat.slug] = (categoryCounts[cat.slug] || 0) + 1;

    const tagsList = [];
    if (subcategory) tagsList.push(subcategory.toLowerCase());
    const matLower = (p.material || '').toLowerCase();
    if (matLower.includes('sheesham')) tagsList.push('sheesham');
    if (matLower.includes('teak')) tagsList.push('teak');
    if (matLower.includes('marble')) tagsList.push('marble');
    if (matLower.includes('ply')) tagsList.push('plywood');
    if (matLower.includes('rexzin')) tagsList.push('rexzin');

    const features = Array.isArray(p.features)
      ? p.features.filter(Boolean).map((f) => String(f).replace(/^[•\-]\s*/, '').trim()).filter(Boolean)
      : [];

    const description = String(p.description || '').trim();
    const descriptionHtml = `<p>${description.replace(/\n+/g, '</p><p>')}</p>`;

    return {
      id: p.id,
      name,
      slug,
      sku: `ABF-${p.id}`,

      category: cat.slug,
      subcategory,
      categoryId,

      price,
      salePrice: null,
      onSale: false,

      material: titleCase(p.material || 'Premium Material'),
      description,
      descriptionHtml,
      features,

      images,
      lifestyleImage,

      dimensions: parseDimensions(p),
      weight: '',
      seatingCapacity: '',
      colorOptions: '',
      variants: [],

      warranty: '1 Year Manufacturing Warranty',
      careInstructions: 'Wipe clean with a dry cloth. Avoid direct sunlight.',
      deliveryInfo: 'Free delivery inside Kathmandu Valley. Usually dispatches in 3-5 days.',
      assemblyRequired: false,

      tag: idx % 7 === 0 ? 'Bestseller' : 'New',
      inStock: true,
      madeToOrder: false,
      stockStatus: 'in_stock',

      featured,
      published: true,
      tags: tagsList,
      popularity,

      createdAt: now,
      updatedAt: now,
    };
  });

// Build the categories export (slug-keyed, matches HomePage layout).
const categories = {};
for (const c of CATEGORY_META) {
  const count = categoryCounts[c.slug] || 0;
  if (count === 0) continue;
  categories[c.slug] = {
    id: c.id,
    name: c.name,
    slug: c.slug,
    productCount: count,
  };
}

// ---------------------------------------------------------------------------

const header = `/**
 * AB Furniture & Furnishing — Product Catalogue
 * Generated by scripts/build_products_js.cjs — DO NOT EDIT BY HAND.
 * Run \`node scripts/build_products_js.cjs\` to regenerate after changes
 * to products.json or the image manifest.
 */

export const categories = ${JSON.stringify(categories, null, 2)};

export const products = ${JSON.stringify(products, null, 2)};

export const formatNPR = (price) => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'NPR',
    maximumFractionDigits: 0,
  }).format(price);
};
`;

fs.writeFileSync(OUTPUT, header);
console.log(`Wrote ${products.length} products to ${OUTPUT}`);
console.log(`Categories:`, Object.keys(categories).map((k) => `${k}(${categories[k].productCount})`).join(', '));
console.log(`Featured: ${featuredCount}`);
