require('dotenv').config({ path: '.env.local' });
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');
const { createClient } = require('@supabase/supabase-js');

// Configuration
const CARPETS_DIR = 'G:\\My Drive\\Arcchive\\AB Furnitures\\Campaign 6\\Selected Images\\Carpets';
const CLOUD_NAME = process.env.VITE_CLOUDINARY_CLOUD_NAME;
const UPLOAD_PRESET = process.env.VITE_CLOUDINARY_UPLOAD_PRESET;
const UPLOAD_URL = `https://api.cloudinary.com/v1_1/${CLOUD_NAME}/image/upload`;
const SUPABASE_URL = process.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = process.env.VITE_SUPABASE_ANON_KEY;

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

async function uploadToCloudinary(buffer, folder) {
  const formData = new FormData();
  const blob = new Blob([buffer], { type: 'image/webp' });
  formData.append('file', blob, 'image.webp');
  formData.append('upload_preset', UPLOAD_PRESET);
  formData.append('folder', folder);

  const response = await fetch(UPLOAD_URL, {
    method: 'POST',
    body: formData,
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Cloudinary upload failed: ${errText}`);
  }

  const data = await response.json();
  return data.secure_url;
}

function generateSlug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

async function run() {
  console.log('Starting carpet import...');
  const subdirs = fs.readdirSync(CARPETS_DIR, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

  for (const dirName of subdirs) {
    const fullDirPath = path.join(CARPETS_DIR, dirName);
    const files = fs.readdirSync(fullDirPath);
    
    // Find all JPGs
    const jpgFiles = files.filter(f => f.toLowerCase().endsWith('.jpg'));
    if (jpgFiles.length === 0) {
      console.log(`Skipping "${dirName}" - no JPG files found.`);
      continue;
    }
    
    console.log(`\nProcessing "${dirName}" (${jpgFiles.length} images)...`);
    
    // ID and Slug based on folder name
    // e.g. "Blue Carpety" -> slug: carpet-blue-carpety, id: generated by Supabase (or we can use timestamp)
    const baseSlug = 'carpet-' + generateSlug(dirName);
    
    // Check if product already exists (just to be safe)
    const { data: existing } = await supabase.from('products').select('id').eq('slug', baseSlug).single();
    if (existing) {
      console.log(`Product with slug ${baseSlug} already exists. Skipping.`);
      continue;
    }

    // Generate unique ID for cloudinary folder
    const productId = `cat_${Date.now()}_${Math.floor(Math.random() * 1000)}`;

    const uploadedUrls = [];
    let count = 1;

    for (const file of jpgFiles) {
      const filePath = path.join(fullDirPath, file);
      
      console.log(`  - Resizing and cropping ${file}...`);
      try {
        // Crop to square, resize to 1200x1200, compress to WebP
        const processedBuffer = await sharp(filePath)
          .resize({
            width: 1200,
            height: 1200,
            fit: 'cover',
            position: 'center'
          })
          .webp({ quality: 80 })
          .toBuffer();
          
        console.log(`  - Uploading to Cloudinary...`);
        const url = await uploadToCloudinary(processedBuffer, `abf-website/products/${productId}`);
        uploadedUrls.push(url);
        count++;
      } catch (err) {
        console.error(`  - Failed to process/upload ${file}:`, err.message);
      }
    }

    if (uploadedUrls.length === 0) {
      console.log(`Failed to upload any images for "${dirName}". Skipping product creation.`);
      continue;
    }

    // Insert to Supabase
    const productData = {
      id: productId,
      name: "-",
      slug: baseSlug,
      category: "carpets",
      category_id: "cat_carpet",
      price: 1,
      sale_price: null,
      on_sale: false,
      images: uploadedUrls, // Let Supabase handle jsonb
      featured: false,
      published: true,
      description: "",
      material: "Carpet",
      delivery_info: "Free delivery inside Kathmandu Valley",
      stock_status: "in_stock",
      popularity: 0
    };

    const { error } = await supabase.from('products').insert(productData);
    
    if (error) {
      console.error(`❌ Failed to insert product for "${dirName}":`, error.message);
    } else {
      console.log(`✅ Successfully added product for "${dirName}".`);
    }
  }

  console.log('\nFinished all folders.');
}

run().catch(err => {
  console.error("Fatal error:", err);
});
